Avoiding unnecessary get calls
nuvla/python-library pull request #40
Opened 2023-12-11 10:46 UTC by amitbhanja

2023-12-16 00:28 UTC, schaubl commented on code/src/nuvla/api/api.py
> -
Missing new line

2023-12-20 03:10 UTC, amitbhanja commented on code/src/nuvla/api/api.py
> -
Done

2024-01-11 20:52 UTC, konstan requested changes

2024-01-11 20:52 UTC, konstan commented on code/src/nuvla/api/api.py
>          return CimiResource(self._cimi_put(resource_id=operation_href, json=data, params=kwargs))
IMO, having `operation_href` var is unnecessary. I suggest directly providing `resource.id` to the `resource_id` kwarg.

2024-01-11 20:52 UTC, konstan commented on code/src/nuvla/api/api.py
>          return CimiResponse(self._cimi_delete(resource_id=operation_href))
IMO, having `operation_href` var is unnecessary. I suggest directly providing `resource.id` to the `resource_id` kwarg.

2024-01-11 20:52 UTC, konstan commented on code/src/nuvla/api/api.py
Why f-string needs to be used? Is `id` on the `collection` not of type str? And also, I don't see a need for the intermediary `operation_href` var.

2024-01-11 20:52 UTC, konstan commented on code/src/nuvla/api/api.py
Instead, the above can be done as `return resource_id or resource_type`.

2024-01-16 15:28 UTC, merged